### ISSUE TITLE
No pages were found in the folders

### ISSUE THREAD

**Issue by sajjadalis** [Spladenly/ai-manga-upscale-colab#1]
Hi,

I uploaded a cbz file in `ESRGAN/input` and it was extracted successfully in its own folder but when I tried the script, it gave this error.

```
No pages were found in the folders: '/ESRGAN/input' and '/ESRGAN/input-color' on your Google Drive.
Please upload manga pages there, and run this script again.
```
I thought maybe, the volume's own folder might be the issue, so I moved all PNG images to `ESRGAN/input` and tried to run the script again but same issue. Also tried to reconnect the Google Drive. It's not working.

**Comment by Spladenly** [comment]
Should be fixed now! Turned out that due to incorrect logic, the script was expecting pages in both input and input-color directories. Now it doesn't. If something related to this still doesn't work -- feel free to reopen this issue.
