### ISSUE TITLE
Resize and Output Format Options?

### ISSUE THREAD

**Issue by sajjadalis** [Spladenly/ai-manga-upscale-colab#4]
Is it possible to include an input field option for resizing images based on a percentage of the original size? Currently, the images are upscaled to 4x their original dimensions, but having the ability to set this to 2x, 3x, or other values would be highly beneficial. This is crucial because the output files are becoming exceptionally large. For instance, an image with a width of 1111px is being resized to 4444px, resulting in a file size of 37MB for a single image. This resizing process is also time-consuming leads to runtime disconnection and creates storage issues as well.

In addition, having the option to set the output format as JPG with a quality adjustment setting would be a valuable addition, although not as critical.

**Comment by Spladenly** [comment]
Unfortunately, this isn't possible. The AI models used here are specifically trained to upscale images 4 times. You can't just select by how many times you want it to upscale. So, there isn't really a way to change this without re-training those models which isn't really an option.

The only solution I see here is to use imagemagick to downscale them in batch afterwards. But the problem with this approach is that it's going to take additional time, storage space, and there isn't much sense running this on a notebook with a GPU. So, aside from creating another CPU-only notebook for downscaling I don't think there's much to do.

**Comment by sajjadalis** [comment]
I understand. Thanks for your response.

You're correct, there is no need to use ImageMagick. I think the only way to use ImageMagick (as an optional step) is within the loop to resize the upscaled image and then delete the 4x file could be a workaround to manage storage. However, it will take additional time and will not address the runtime disconnection issue when upscaling multiple volumes.

**Comment by sajjadalis** [comment]
> So, aside from creating another CPU-only notebook for downscaling I don't think there's much to do.

Yes, creating a separate CPU-only notebook for downscaling seems like a viable solution. This approach not only simplifies manual resizing (which I'm currently doing with ImageMagick mogrify) but also helps with downloading those large volume files (which is around 5GB per volume)
